from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum

class ProviderEnum(str, Enum):
    GOOGLE = "google"
    GROQ = "groq"
    INFERENCE = "inference"

class Message(BaseModel):
    role: str = Field(..., description="The role of the message author (e.g., user, assistant, system)")
    content: str = Field(..., description="The content of the message")

class ChatRequest(BaseModel):
    provider: ProviderEnum = Field(default=ProviderEnum.GROQ, description="The LLM provider to route the message to")
    messages: List[Message] = Field(..., description="The chat history containing the message exchange")
    temperature: Optional[float] = Field(default=0.7, ge=0.0, le=2.0, description="The sampling temperature")

class ChatResponse(BaseModel):
    message: Message = Field(..., description="The response message generated by the assistant")
    provider: str = Field(..., description="The provider that responded to the request")
    model: str = Field(..., description="The exact model name used to generate the response")
